apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: auditor2-peer0
  namespace: auditor2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: auditor2-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev-test
        namespace: flux-dev-test
      chart: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: auditor2-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
        
    peer:
      name: peer0
      gossippeeraddress: peer0.auditor2-net:7051
      gossipexternalendpoint: peer0.auditor2-net:7051
      localmspid: auditor2MSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: auditor2-user

    storage:
      peer:
        storageclassname: auditor2sc
        storagesize: 1Gi
      couchdb:
        storageclassname: auditor2sc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://a3c430e7cb6d24101809f2d08fb11797-1757273231.eu-west-1.elb.amazonaws.com:8200
      authpath: dev-testauditor2-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/auditor2-net/peers/peer0.auditor2-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/auditor2-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/auditor2-net/couchdb/auditor2?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "none"
      external_url_suffix: develop.local.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
